#import <Foundation/Foundation.h>
#import "SWGHLRCallback.h"
#import "SWGHLRError.h"
#import "SWGHLRResult.h"
#import "SWGOutOfCredit.h"
#import "SWGApi.h"

/**
* SMS Fusion API
* This is the SMS Fusion API
*
* OpenAPI spec version: 1.0.0
* Contact: support@smsfusion.com.au
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGDefaultApi: NSObject <SWGApi>

extern NSString* kSWGDefaultApiErrorDomain;
extern NSInteger kSWGDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// HLR number lookup
/// Perform HLR on number
///
/// @param key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
/// @param num A single phone number or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;
/// @param cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally (optional)
/// 
///  code:200 message:"Successfull response without callback URL",
///  code:401 message:"Authentication failed or paramaters not provided",
///  code:429 message:"Out of credit"
///
/// @return SWGHLRCallback*
-(NSURLSessionTask*) getHLRWithKey: (NSString*) key
    num: (NSString*) num
    cc: (NSString*) cc
    completionHandler: (void (^)(SWGHLRCallback* output, NSError* error)) handler;


/// HLR number lookup with results going to a callback URL
/// Perform HLR on number with the result being sent to the callback URL provided
///
/// @param key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
/// @param num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s
/// @param cb HTTP or HTTPS callback URL for each result. The result will be sent as POST with a json object included in &lt;b&gt;result&lt;/b&gt;. Timeout for callbacks is set to 30 seconds
/// @param cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally (optional)
/// 
///  code:200 message:"Responses will be sent to the callback URL as a POST in the result= field",
///  code:401 message:"Authentication failed or paramaters not provided",
///  code:429 message:"Out of credit"
///
/// @return SWGHLRResult*
-(NSURLSessionTask*) getHLRCallbackWithKey: (NSString*) key
    num: (NSArray<NSString*>*) num
    cb: (NSString*) cb
    cc: (NSString*) cc
    completionHandler: (void (^)(SWGHLRResult* output, NSError* error)) handler;



@end
