#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* SMS Fusion API
* This is the SMS Fusion API
*
* OpenAPI spec version: 1.0.0
* Contact: support@smsfusion.com.au
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGHLRResult
@end

@interface SWGHLRResult : SWGObject


@property(nonatomic) NSString* status;

@property(nonatomic) NSArray<NSNumber*>* success;

@property(nonatomic) NSArray<NSNumber*>* failure;
/* Cost of the response [optional]
 */
@property(nonatomic) NSNumber* cost;
/* Callback URL provided [optional]
 */
@property(nonatomic) NSString* callback;

@end
