#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* SMS Fusion API
* This is the SMS Fusion API
*
* OpenAPI spec version: 1.0.0
* Contact: support@smsfusion.com.au
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGHLRCallback
@end

@interface SWGHLRCallback : SWGObject

/* Unique ID for response [optional]
 */
@property(nonatomic) NSString* _id;
/* The MSISDN of the number queried [optional]
 */
@property(nonatomic) NSNumber* msisdn;
/* Short status code of the response [optional]
 */
@property(nonatomic) NSString* status;
/* ISO 3166-2 country code [optional]
 */
@property(nonatomic) NSString* country;
/* The operator attached to the MSISDN [optional]
 */
@property(nonatomic) NSString* operator;
/* MCC and MNC of MSDISDN [optional]
 */
@property(nonatomic) NSNumber* mccmnc;
/* If the response code is temporary or permenant [optional]
 */
@property(nonatomic) NSString* duration;
/* Full status code of the response [optional]
 */
@property(nonatomic) NSString* message;
/* Extended explanation of the status code [optional]
 */
@property(nonatomic) NSString* extended;
/* Cost of the response [optional]
 */
@property(nonatomic) NSNumber* cost;

@end
