#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* SMS Fusion API
* This is the SMS Fusion API
*
* OpenAPI spec version: 1.0.0
* Contact: support@smsfusion.com.au
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGOutOfCredit
@end

@interface SWGOutOfCredit : SWGObject

/* Description of error [optional]
 */
@property(nonatomic) NSString* error;

@end
