#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* SMS Fusion API
* This is the SMS Fusion API
*
* OpenAPI spec version: 1.0.0
* Contact: support@smsfusion.com.au
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGSMSResult
@end

@interface SWGSMSResult : SWGObject

/* Unique ID for response [optional]
 */
@property(nonatomic) NSString* _id;
/* Count of queued SMS [optional]
 */
@property(nonatomic) NSNumber* success;
/* Cost of the SMS [optional]
 */
@property(nonatomic) NSNumber* cost;
/* Total count of SMS queued [optional]
 */
@property(nonatomic) NSNumber* count;
/* List of failed numbers [optional]
 */
@property(nonatomic) NSArray<NSString*>* failure;

@end
